import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}} bg-slate-950 overflow-auto h-screen max-h-screen`}>
        <div className="mx-auto max-w-screen-md flex flex-col items-start justify-center bg-slate-900 border-l border-r border-slate-700">
          <Header />
          <div className="w-full" style={{ minHeight: 'calc(100vh - 64px)'}}>
            {children}
          </div>
        </div>
        <div id="modal-target"></div>
      </body>
    </html>
  );
}
